### ISSUE TITLE
Error in running plotter.py 

### ISSUE THREAD

**Issue by chinmayeeb96** [varuns23/monoJetTools#1]
Hi, Really appreciate the work you have done, I am using this repo as my reference for my master's project.

After I ran the code particularly 
python PlotTool/plotter.py recoil -a 1

I am defining path to post files with this method:
`Region(path="monoJetTools/2017/DoubleMuCR/")`

However, I am getting error in the following line
`tfile = next( process[0].tfile for process in self if process[0].tfile is not None )`

StopIteration error as we are getting empty generator from the line and process[0] doesn't contain tfile method.

Can you please suggest to me how to fix this error ??

**Comment by ekoenig4** [comment]
Are you sure that is the correct path? If you are running from the monoJetTools directory, the path should be 

```
Region(path="2017/DoubleMuCR")
```
You can run the plotter with 
```
python PlotTool/plotter.py recoil -a 1 --verbose 1
```
and it should print out if it wasn't able to find the files in the path you specified.

**Comment by chinmayeeb96** [comment]
Hi, I tried with the same still getting the same error also not getting any log that could indicate the error. 
For debugging purposes, I did some extra print statements.

`
print('*****',[process for process in self])
print([process[0] for process in self ])
`

If you can suggest what I am doing wrong that would be excellent.

Please find the error log.
***********************************************************
monoJetTools]$ python PlotTool/plotter.py recoil -a 1 --verbose 1
Using /afs/hep.wisc.edu/user/bsahu/ProjectStudent_HCU/Chinmayee/Monojet/CMSSW_10_2_18/src/monoJetTools/2017/DoubleMuCR
Plotting recoil
skipping
Blinded: Setting data as SumOfBkg
('*****', [])
[]
Traceback (most recent call last):
  File "PlotTool/plotter.py", line 230, in <module>
    if parser.args.run2 is None: plotter()
  File "PlotTool/plotter.py", line 196, in plotter
    plotVariable(samples,variable)
  File "PlotTool/plotter.py", line 48, in plotVariable
    samples.initiate(variable)
  File "/afs/hep.wisc.edu/user/bsahu/ProjectStudent_HCU/Chinmayee/Monojet/CMSSW_10_2_18/src/monoJetTools/PlotTool/PlotTool/Region.py", line 277, in initiate
    self.initVariable(variable,weight,cut)
  File "/afs/hep.wisc.edu/user/bsahu/ProjectStudent_HCU/Chinmayee/Monojet/CMSSW_10_2_18/src/monoJetTools/PlotTool/PlotTool/Region.py", line 256, in initVariable
    tfile = next( process[0].tfile for process in self if process[0].tfile is not None )
StopIteration
`

**Comment by ekoenig4** [comment]
It looks like your post files are in the wrong place. The post files should be in the Region directory, not the output folder, so it wasn't able to find any of the files.

**Comment by chinmayeeb96** [comment]
Thanks for all the help. It worked.
